### ISSUE TITLE
Would it be okay if I use your code?

### ISSUE THREAD

**Issue by jeff-hykin** [zsedem/sha256-rust#2]
I'd like to use your implementation in a school project, but there's no license.

**Comment by zsedem** [comment]
sure, do whatever you want with it, let me add a copyright at the beginning of the file

BTW.: there isn't too much thing to copyright, because an algorithm itself is not copyrightable, so legally speaking if you just using the code as a guideline for implementing the algorithm you should be fine

**Comment by jeff-hykin** [comment]
Great thank you!
